### ISSUE TITLE
High latencies when one CRA worker has connections with many offline CRA workers

### ISSUE THREAD

**Issue by nlebeck** [microsoft/CRA#11]
When a CRA worker has established connections with several other CRA workers, and many of those other workers are offline, its connections with the online workers take a long time to get established and have high latency.

I have noticed this behavior when working with AMBROSIA applications with a client/server architecture. A typical configuration is 10 clients that are each connected to a single server through CRA. If I initially spin up all 10 clients and the server, kill all nodes, and then start up the server and a single client, their connection takes several seconds to finish being established, and that connection has high latency even after it is set up.

**Comment by badrishc** [comment]
Issue seems to not exist in the latest version. Closing.
