### ISSUE TITLE
Open source the Quill project

### ISSUE THREAD

**Issue by MedAnd** [microsoft/CRA#12]
As the Quill project is built using the CRA and the [Trill ](https://github.com/microsoft/Trill) library which are now both open source projects, please consider open sourcing the Quill project.

Links

- [Distributed Trill support](https://github.com/microsoft/Trill/issues/92)

**Comment by badrishc** [comment]
Good timing for the ask, actually. Our collaborator and former intern @ibrahimsabek has been working on a prototype port of Quill to work on CRA. He should have the sample here in the next few weeks to play with.

**Comment by ArcadeMode** [comment]
Hi! Has a Quill port to CRA been made available yet? Would love to experiment with it 😄

**Comment by InCerryGit** [comment]
Hi! Is there any progress now?
